//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34014 版自动生成。
// 
#pragma warning disable 1591

namespace Mfg.EI.InterFace.GoodPaper {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tsjAPISoap", Namespace="http://tempuri.org/")]
    public partial class tsjAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPaperListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPapersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaperSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaperDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDownPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tsjAPI() {
            this.Url = global::Mfg.EI.InterFace.Properties.Settings.Default.Mfg_EI_InterFace_GoodPaper_tsjAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPaperListCompletedEventHandler GetPaperListCompleted;
        
        /// <remarks/>
        public event GetPapersCompletedEventHandler GetPapersCompleted;
        
        /// <remarks/>
        public event GetPaperSearchCompletedEventHandler GetPaperSearchCompleted;
        
        /// <remarks/>
        public event GetPaperDetailCompletedEventHandler GetPaperDetailCompleted;
        
        /// <remarks/>
        public event GetDownPathCompletedEventHandler GetDownPathCompleted;
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPaperList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ETaoPaper[] GetPaperList(string key, string sub, string sgrade, string term, string type, string edition, int pno, int pageSize, string order, out int allct) {
            object[] results = this.Invoke("GetPaperList", new object[] {
                        key,
                        sub,
                        sgrade,
                        term,
                        type,
                        edition,
                        pno,
                        pageSize,
                        order});
            allct = ((int)(results[1]));
            return ((ETaoPaper[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPaperListAsync(string key, string sub, string sgrade, string term, string type, string edition, int pno, int pageSize, string order) {
            this.GetPaperListAsync(key, sub, sgrade, term, type, edition, pno, pageSize, order, null);
        }
        
        /// <remarks/>
        public void GetPaperListAsync(string key, string sub, string sgrade, string term, string type, string edition, int pno, int pageSize, string order, object userState) {
            if ((this.GetPaperListOperationCompleted == null)) {
                this.GetPaperListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaperListOperationCompleted);
            }
            this.InvokeAsync("GetPaperList", new object[] {
                        key,
                        sub,
                        sgrade,
                        term,
                        type,
                        edition,
                        pno,
                        pageSize,
                        order}, this.GetPaperListOperationCompleted, userState);
        }
        
        private void OnGetPaperListOperationCompleted(object arg) {
            if ((this.GetPaperListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaperListCompleted(this, new GetPaperListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPapers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ETaoPaper[] GetPapers(string key, string sub, int[] ids, int pno, int pageSize) {
            object[] results = this.Invoke("GetPapers", new object[] {
                        key,
                        sub,
                        ids,
                        pno,
                        pageSize});
            return ((ETaoPaper[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPapersAsync(string key, string sub, int[] ids, int pno, int pageSize) {
            this.GetPapersAsync(key, sub, ids, pno, pageSize, null);
        }
        
        /// <remarks/>
        public void GetPapersAsync(string key, string sub, int[] ids, int pno, int pageSize, object userState) {
            if ((this.GetPapersOperationCompleted == null)) {
                this.GetPapersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPapersOperationCompleted);
            }
            this.InvokeAsync("GetPapers", new object[] {
                        key,
                        sub,
                        ids,
                        pno,
                        pageSize}, this.GetPapersOperationCompleted, userState);
        }
        
        private void OnGetPapersOperationCompleted(object arg) {
            if ((this.GetPapersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPapersCompleted(this, new GetPapersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPaperSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ETaoPaper[] GetPaperSearch(string key, string sub, string text, int pno, int pageSize, out int allct) {
            object[] results = this.Invoke("GetPaperSearch", new object[] {
                        key,
                        sub,
                        text,
                        pno,
                        pageSize});
            allct = ((int)(results[1]));
            return ((ETaoPaper[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPaperSearchAsync(string key, string sub, string text, int pno, int pageSize) {
            this.GetPaperSearchAsync(key, sub, text, pno, pageSize, null);
        }
        
        /// <remarks/>
        public void GetPaperSearchAsync(string key, string sub, string text, int pno, int pageSize, object userState) {
            if ((this.GetPaperSearchOperationCompleted == null)) {
                this.GetPaperSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaperSearchOperationCompleted);
            }
            this.InvokeAsync("GetPaperSearch", new object[] {
                        key,
                        sub,
                        text,
                        pno,
                        pageSize}, this.GetPaperSearchOperationCompleted, userState);
        }
        
        private void OnGetPaperSearchOperationCompleted(object arg) {
            if ((this.GetPaperSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaperSearchCompleted(this, new GetPaperSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPaperDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ETaoPaper GetPaperDetail(string key, string sub, string id) {
            object[] results = this.Invoke("GetPaperDetail", new object[] {
                        key,
                        sub,
                        id});
            return ((ETaoPaper)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaperDetailAsync(string key, string sub, string id) {
            this.GetPaperDetailAsync(key, sub, id, null);
        }
        
        /// <remarks/>
        public void GetPaperDetailAsync(string key, string sub, string id, object userState) {
            if ((this.GetPaperDetailOperationCompleted == null)) {
                this.GetPaperDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaperDetailOperationCompleted);
            }
            this.InvokeAsync("GetPaperDetail", new object[] {
                        key,
                        sub,
                        id}, this.GetPaperDetailOperationCompleted, userState);
        }
        
        private void OnGetPaperDetailOperationCompleted(object arg) {
            if ((this.GetPaperDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaperDetailCompleted(this, new GetPaperDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDownPath", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDownPath(string key, string sub, string id) {
            object[] results = this.Invoke("GetDownPath", new object[] {
                        key,
                        sub,
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDownPathAsync(string key, string sub, string id) {
            this.GetDownPathAsync(key, sub, id, null);
        }
        
        /// <remarks/>
        public void GetDownPathAsync(string key, string sub, string id, object userState) {
            if ((this.GetDownPathOperationCompleted == null)) {
                this.GetDownPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDownPathOperationCompleted);
            }
            this.InvokeAsync("GetDownPath", new object[] {
                        key,
                        sub,
                        id}, this.GetDownPathOperationCompleted, userState);
        }
        
        private void OnGetDownPathOperationCompleted(object arg) {
            if ((this.GetDownPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDownPathCompleted(this, new GetDownPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void test() {
            this.Invoke("test", new object[0]);
        }
        
        /// <remarks/>
        public void testAsync() {
            this.testAsync(null);
        }
        
        /// <remarks/>
        public void testAsync(object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[0], this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ETaoPaper {
        
        private string p_idField;
        
        private string p_nameField;
        
        private string p_clickField;
        
        private string p_classField;
        
        private string p_intimeField;
        
        private string p_type1Field;
        
        private string p_area1Field;
        
        private string p_yearField;
        
        private string p_edition1Field;
        
        private string p_detailpathField;
        
        private string p_flashpathField;
        
        private string p_flashsizeField;
        
        private string p_pagesizeField;
        
        private string p_inmanField;
        
        private string p_wordpathField;
        
        /// <remarks/>
        public string p_id {
            get {
                return this.p_idField;
            }
            set {
                this.p_idField = value;
            }
        }
        
        /// <remarks/>
        public string p_name {
            get {
                return this.p_nameField;
            }
            set {
                this.p_nameField = value;
            }
        }
        
        /// <remarks/>
        public string p_click {
            get {
                return this.p_clickField;
            }
            set {
                this.p_clickField = value;
            }
        }
        
        /// <remarks/>
        public string p_class {
            get {
                return this.p_classField;
            }
            set {
                this.p_classField = value;
            }
        }
        
        /// <remarks/>
        public string p_intime {
            get {
                return this.p_intimeField;
            }
            set {
                this.p_intimeField = value;
            }
        }
        
        /// <remarks/>
        public string p_type1 {
            get {
                return this.p_type1Field;
            }
            set {
                this.p_type1Field = value;
            }
        }
        
        /// <remarks/>
        public string p_area1 {
            get {
                return this.p_area1Field;
            }
            set {
                this.p_area1Field = value;
            }
        }
        
        /// <remarks/>
        public string p_year {
            get {
                return this.p_yearField;
            }
            set {
                this.p_yearField = value;
            }
        }
        
        /// <remarks/>
        public string p_edition1 {
            get {
                return this.p_edition1Field;
            }
            set {
                this.p_edition1Field = value;
            }
        }
        
        /// <remarks/>
        public string p_detailpath {
            get {
                return this.p_detailpathField;
            }
            set {
                this.p_detailpathField = value;
            }
        }
        
        /// <remarks/>
        public string p_flashpath {
            get {
                return this.p_flashpathField;
            }
            set {
                this.p_flashpathField = value;
            }
        }
        
        /// <remarks/>
        public string p_flashsize {
            get {
                return this.p_flashsizeField;
            }
            set {
                this.p_flashsizeField = value;
            }
        }
        
        /// <remarks/>
        public string p_pagesize {
            get {
                return this.p_pagesizeField;
            }
            set {
                this.p_pagesizeField = value;
            }
        }
        
        /// <remarks/>
        public string p_inman {
            get {
                return this.p_inmanField;
            }
            set {
                this.p_inmanField = value;
            }
        }
        
        /// <remarks/>
        public string p_wordpath {
            get {
                return this.p_wordpathField;
            }
            set {
                this.p_wordpathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetPaperListCompletedEventHandler(object sender, GetPaperListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaperListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaperListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ETaoPaper[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ETaoPaper[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int allct {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetPapersCompletedEventHandler(object sender, GetPapersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPapersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPapersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ETaoPaper[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ETaoPaper[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetPaperSearchCompletedEventHandler(object sender, GetPaperSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaperSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaperSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ETaoPaper[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ETaoPaper[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int allct {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetPaperDetailCompletedEventHandler(object sender, GetPaperDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaperDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaperDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ETaoPaper Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ETaoPaper)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetDownPathCompletedEventHandler(object sender, GetDownPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDownPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDownPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void testCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591